language: python

matrix:
  include:
    - name: "Python 3.7 Unit Tests"
      python: 3.7
      env: TOXENV=py37
    - name: "Linter"
      python: 3.7
      env: TOXENV=lint

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls
