PERIODS_PER_YEAR = 12


def yearly_to_period_rate(yearly_rate):
    return yearly_rate / PERIODS_PER_YEAR


DEFAULT_MORTGAGE_YEARS = 30
DEFAULT_MORTGAGE_APR = 0.03
DEFAULT_MORTGAGE_RATE = yearly_to_period_rate(DEFAULT_MORTGAGE_APR)

DEFAULT_INVESTMENT_RETURN = 0.04
DEFAULT_INVESTMENT_RETURN_RATE = yearly_to_period_rate(DEFAULT_INVESTMENT_RETURN)

DEFAULT_HOME_APPRECIATION = 0.02
DEFAULT_HOME_APPRECIATION_RATE = yearly_to_period_rate(DEFAULT_HOME_APPRECIATION)

DEFAULT_DOWN_PAYMENT_PCT = 0.20

DEFAULT_HOME_BUYING_COSTS_PCT = 0.04
DEFAULT_HOME_SELLING_COSTS_PCT = 0.06
DEFAULT_HOME_MAINTENANCE_PCT = 0.01
DEFAULT_HOME_MAINTENANCE_RATE = yearly_to_period_rate(DEFAULT_HOME_MAINTENANCE_PCT)

DEFAULT_HOME_INURANCE_PCT = 0.0050

DEFAULT_PROPERTY_TAX_PCT = 0.0125

DEFAULT_RENT_INCREASE_PCT = 0.025

INIT_PERIOD = -1
NEVER_PERIOD = -2
